

<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$storeScope = \Magento\Store\Model\ScopeInterface::SCOPE_STORES;
$scopeConfig = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface');

$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');

$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);

$inscricao_estadual = "";
$rasao_social = "";
$taxvat = "";
$tipo_pessoa = 1;
if($customerSession->isLoggedIn()) {
    $tipo_pessoa = $customerSession->getCustomer()->getTipoPessoa();
    $rasao_social = $customerSession->getCustomer()->getRasaoSocial();
    $inscricao_estadual = $customerSession->getCustomer()->getInscricaoEstadual();
    $taxvat = $customerSession->getCustomer()->getTaxvat();
}

?>
<?php if($scopeConfig->getValue("mmcpfcnpj/geral/ativarmodulo", $storeScope)): ?>

    <script>
        var tipo_pessoa_s = "<?=$tipo_pessoa?>";
        var rasao_social_s = "<?=$rasao_social?>";
        var inscricao_estadual_s = "<?=$inscricao_estadual?>";
        var taxvat_s = "<?=$taxvat?>";

        var drop_down, razao_social, inscricao_estadual, taxvat,valid_ok;

        require(['jquery', 'jquery/ui'], function($){
            $( document ).ready(function() {

                //wait until the last element (.payment-method) being rendered
                var existCondition = setInterval(function() {

                     drop_down = $('.form-shipping-address [name*="shippingAddress.drop_down"] [name*="drop_down"]');
                     razao_social = $('.form-shipping-address [name*="shippingAddress.razao_social"] input[name*="razao_social"]');
                     inscricao_estadual = $('.form-shipping-address [name*="shippingAddress.inscricao_estadual"] input[name*="inscricao_estadual"]');
                     taxvat = $('.form-shipping-address [name*="shippingAddress.vat_id"] input[name*="vat_id"]');

                    if (drop_down.length && taxvat.length) {
                        clearInterval(existCondition);


                        drop_down.val(tipo_pessoa_s);
                        razao_social.val(rasao_social_s);
                        inscricao_estadual.val(inscricao_estadual_s);
                        taxvat.val(taxvat_s);
                        taxvat.trigger('keyup');

                        changeImput();

                        drop_down.change(function() {
                            changeImput();
                            taxvat.val('');
                            tipo_pessoa_s = $(this).val();
                            changeAtribute('tipo_pessoa',$(this).val())
                        });

                        razao_social.change(function() {
                            changeAtribute('rasao_social',$(this).val())
                        });
                        inscricao_estadual.change(function() {
                            changeAtribute('inscricao_estadual',$(this).val())
                        });

                        taxvat.keyup(function() {
                            taxvat.val(cpfCnpj(taxvat.val()))
                        });

                        taxvat.change(function() {
                            buscarTaxVat($(this).val())
                        });

                    }

                    function buscarTaxVat(val) {
                        validaCampo(val);
                        <?php if($scopeConfig->getValue("mmcpfcnpj/loja/taxvat_unico", $storeScope)): ?>

                        if(validaCampo(val)) {
                            valid_ok = true;
                            var xmlhttp = new XMLHttpRequest();
                            xmlhttp.onreadystatechange = function () {
                                if (this.readyState == 4 && this.status == 200) {

                                    var taxvat = document.querySelector('.form-shipping-address [name*="shippingAddress.vat_id"] [name*="vat_id"]');
                                    var drop_down = document.querySelector('.form-shipping-address [name*="shippingAddress.drop_down"] [name*="drop_down"]');

                                    var labelTipoDoc = '';
                                    if (drop_down.value == 1) {
                                        labelTipoDoc = 'CPF';
                                    } else {
                                        labelTipoDoc = 'CNPJ';
                                    }

                                    if (this.responseText == 1) {

                                        if (!document.querySelector('.cpf-cnpj-mm')) {
                                            taxvat.insertAdjacentHTML('afterend', '<div class="field-error cpf-cnpj-mm" data-bind="attr: { id: element.errorId }" generated="true" id="cpf-cnpj-mm"><span data-bind="text: element.error">' + labelTipoDoc + ' já cadastrado, <a href="<?php echo  $baseUrl ?>customer/account/forgotpassword/"> clique aqui para se logar </a> </span></div>');
                                        }
                                        taxvat.style.border = "1px solid #ed8380";
                                        document.querySelector('.cpf-cnpj-mm').style.display = "Block";

                                        valid_ok = true;
                                    } else {
                                        if (document.querySelector('.cpf-cnpj-mm')) {
                                            document.querySelector('.cpf-cnpj-mm').style.display = "none";
                                        }


                                        valid_ok= false;

                                        taxvat.style.border = "1px solid #c2c2c2";
                                    }


                                }
                            };
                            xmlhttp.open("GET", "<?php echo  $baseUrl ?>mestremage_cpfcnpj?taxvat=" + val + "&_=" + Date.now(), true);
                            xmlhttp.send();
                        }
                        <?php endif; ?>
                    }


                    function changeImput(){
                       var razao_social = $('.form-shipping-address [name*="shippingAddress.razao_social"]');
                       var inscricao_estadual = $('.form-shipping-address [name*="shippingAddress.inscricao_estadual"]');
                        var  lblTaxvat = $('.form-shipping-address [name*="shippingAddress.vat_id"] label.label');
                        var taxvat = $('.form-shipping-address [name*="shippingAddress.vat_id"] [name*="vat_id"]');
                        if(drop_down.val() == 2){
                            razao_social.show();
                            inscricao_estadual.show();
                            lblTaxvat.html('<span data-bind="text: element.label" class="mm-cpf-cnpj">CNPJ</span>');
                            taxvat.attr('maxlength','18');
							taxvat.attr('placeholder','CNPJ');
                        }else{
                            razao_social.hide();
                            inscricao_estadual.hide();
                            lblTaxvat.html('<span data-bind="text: element.label" class="mm-cpf-cnpj">CPF</span>');
                            taxvat.attr('maxlength','14');
							taxvat.attr('placeholder','CPF');
                        }
                    }
                }, 100);



            });
        });







        function cpfCnpj(v){
            v=v.replace(/\D/g,"");
            if (v.length > 0 && v.length <= 11) {
                //CPF
                v=v.replace(/(\d{3})(\d)/,"$1.$2");
                v=v.replace(/(\d{3})(\d)/,"$1.$2");
                v=v.replace(/(\d{3})(\d{1,2})$/,"$1-$2")
            } else {
                //CNPJ
                v=v.replace(/^(\d{2})(\d)/,"$1.$2");
                v=v.replace(/^(\d{2})\.(\d{3})(\d)/,"$1.$2.$3");
                v=v.replace(/\.(\d{3})(\d)/,".$1/$2");
                v=v.replace(/(\d{4})(\d)/,"$1-$2");
            }
            return v
        }
    </script>
    <style>
        .form-shipping-address [name$="shippingAddress.vat_id"] label.label em.required-symbol {
            display: block;
        }
        span.mm-cpf-cnpj:after {
            content: '*';
            color: #e02b27;
            font-size: 1.2rem;
            margin: 0 0 0 5px;
        }
    </style>
<?php endif; ?>



<script>
    function sucessReturn(){
        var taxvat = document.querySelector('.form-shipping-address [name*="shippingAddress.vat_id"] [name*="vat_id"]');
        if(document.querySelector('.cpf-cnpj-mm-val')){
            document.querySelector('.cpf-cnpj-mm-val').style.display = "none";
        }
        valid_ok = false;
        taxvat.style.border = "1px solid #c2c2c2";
    }
    function errorReturn(){
        var taxvat = document.querySelector('.form-shipping-address [name*="shippingAddress.vat_id"] [name*="vat_id"]');
        taxvat.value = "";
        valid_ok = true;
        taxvat.style.border = "1px solid #ed8380";
        if (!document.querySelector('.cpf-cnpj-mm-val')) {
            taxvat.insertAdjacentHTML('afterend', '<div class="field-error cpf-cnpj-mm-val" data-bind="attr: { id: element.errorId }" generated="true" id="cpf-cnpj-mm-val"><span data-bind="text: element.error"> CPF/CNPJ Inválido </span></div>');
        }
        document.querySelector('.cpf-cnpj-mm-val').style.display = "Block";
    }
    function validaCampo(object) {

        if(object.indexOf("11111")!=-1 ||
            object.indexOf("22222")!=-1 ||
            object.indexOf("33333")!=-1 ||
            object.indexOf("44444")!=-1 ||
            object.indexOf("55555")!=-1 ||
            object.indexOf("66666")!=-1 ||
            object.indexOf("77777")!=-1 ||
            object.indexOf("88888")!=-1 ||
            object.indexOf("99999")!=-1) {
            errorReturn();
            }

        if (object.length <= 14) {
            if(tipo_pessoa_s == 2){
                errorReturn();
                return false;
            }else{
                return ValidarCPF(object)
            }
        } else {
          return ValidarCNPJ(object)
        }
    }
    //valida o CPF digitado
    function ValidarCPF(Objcpf) {
        var taxvat = document.querySelector('.form-shipping-address [name*="shippingAddress.vat_id"] [name*="vat_id"]');
        var cpf = Objcpf;
       var exp = /\.|\-/g;
        cpf = cpf.toString().replace(exp, "");


        if (VerificaCPF(cpf)) {
            sucessReturn();
        } else {
            errorReturn();
        }
        return VerificaCPF(cpf);
    }
    //valida o CNPJ digitado
    function ValidarCNPJ(ObjCnpj) {
        var taxvat = document.querySelector('.form-shipping-address [name*="shippingAddress.vat_id"] [name*="vat_id"]');
        var cnpj = ObjCnpj;
        var valida = new Array(6, 5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2);
        var dig1 = new Number;
        var dig2 = new Number;

        exp = /\.|\-|\//g;
        cnpj = cnpj.toString().replace(exp, "");
        var digito = new Number(eval(cnpj.charAt(12) + cnpj.charAt(13)));

        for (i = 0; i < valida.length; i++) {
            dig1 += (i > 0 ? (cnpj.charAt(i - 1) * valida[i]) : 0);
            dig2 += cnpj.charAt(i) * valida[i];
        }
        dig1 = (((dig1 % 11) < 2) ? 0 : (11 - (dig1 % 11)));
        dig2 = (((dig2 % 11) < 2) ? 0 : (11 - (dig2 % 11)));

        if (((dig1 * 10) + dig2) != digito) {
            errorReturn();
            return false;
        } else {
            sucessReturn();
            return true;
        }

    }


    function VerificaCPF(strCpf) {

        var soma;
        var resto;
        soma = 0;
        if (strCpf == "00000000000") {
            return false;
        }

        for (i = 1; i <= 9; i++) {
            soma = soma + parseInt(strCpf.substring(i - 1, i)) * (11 - i);
        }

        resto = soma % 11;

        if (resto == 10 || resto == 11 || resto < 2) {
            resto = 0;
        } else {
            resto = 11 - resto;
        }

        if (resto != parseInt(strCpf.substring(9, 10))) {
            return validarCpf2(strCpf);
        }

        soma = 0;

        for (i = 1; i <= 10; i++) {
            soma = soma + parseInt(strCpf.substring(i - 1, i)) * (12 - i);
        }
        resto = soma % 11;

        if (resto == 10 || resto == 11 || resto < 2) {
            resto = 0;
        } else {
            resto = 11 - resto;
        }

        if (resto != parseInt(strCpf.substring(10, 11))) {
            return validarCpf2(strCpf);
        }

        return true;
    }


    function validarCpf2(strCPF) {
        var Soma;
        var Resto;
        Soma = 0;
        if (strCPF == "00000000000") return false;

        for (i=1; i<=9; i++) Soma = Soma + parseInt(strCPF.substring(i-1, i)) * (11 - i);
        Resto = (Soma * 10) % 11;

        if ((Resto == 10) || (Resto == 11))  Resto = 0;
        if (Resto != parseInt(strCPF.substring(9, 10)) ) return false;

        Soma = 0;
        for (i = 1; i <= 10; i++) Soma = Soma + parseInt(strCPF.substring(i-1, i)) * (12 - i);
        Resto = (Soma * 10) % 11;

        if ((Resto == 10) || (Resto == 11))  Resto = 0;
        if (Resto != parseInt(strCPF.substring(10, 11) ) ) return false;
        return true;
    }
    function changeAtribute(atr_lbl,atr_value) {
        var xmlhttp = new XMLHttpRequest();
        xmlhttp.onreadystatechange = function() {
            if (this.readyState == 4 && this.status == 200) {
           console.log(this.responseText);
            }
        };
        xmlhttp.open("GET", "<?php echo  $baseUrl ?>mestremage_cpfcnpj?atr_lbl="+atr_lbl+"&atr_value="+atr_value+"&_=" + Date.now(), true);
        xmlhttp.send();
    }
</script>

