<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$storeScope = \Magento\Store\Model\ScopeInterface::SCOPE_STORES;
$scopeConfig = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface');
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');

$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);

$inscricao_estadual = "";
$rasao_social = "";
$taxvat = "";
$tipo_pessoa = 1;
if($customerSession->isLoggedIn()) {
    $tipo_pessoa = $customerSession->getCustomer()->getTipoPessoa();
	$rasao_social = $customerSession->getCustomer()->getRasaoSocial();
	$inscricao_estadual = $customerSession->getCustomer()->getInscricaoEstadual();
	$taxvat = $customerSession->getCustomer()->getTaxvat();
}



?>
<?php if($scopeConfig->getValue("mmcpfcnpj/geral/ativarmodulo", $storeScope)): ?>
<script>
	var htmlCheck,htmlFisica,htmlJuridica;

	htmlCheck = '	<div class="cont_pessoa">';
	htmlCheck += '<label class="checkbox-inline"><input type="radio" id="pessoa_fisica" class="cls_tipo_pessoa" name="ck_tipo_pessoa" value="1" <?php echo ( $tipo_pessoa == 1 ? "checked" : "" ); ?> >Pessoa Física</label>';
	htmlCheck += '<label class="checkbox-inline"><input type="radio" id="pessoa_juridic" class="cls_tipo_pessoa" name="ck_tipo_pessoa" value="2" <?php echo ( $tipo_pessoa == 2 ? "checked" : "" ); ?>>Pessoa Jurídica</label>';
	htmlCheck += '</div>';
	htmlCheck += '<div class="cont_check_mm"></div>';


	htmlFisica = '<label class="label" id="lbl_pessoa_fisica" for="taxvat"><span><?=__('CPF')?></span></label>';
	htmlFisica += '<div class="control">';
	htmlFisica += '	<input type="text" id="taxvat"  onchange="buscarTaxVat(this)" onkeyup="mascaraMutuario(this,cpfCnpj)" name="taxvat" value="" title="<?=__('CPF')?>" class="input-text " data-validate="{required:true}" autocomplete="off" aria-required="true">';
	htmlFisica += '	</div>';
	htmlFisica += '	<input type="hidden" name="tipo_pessoa" value="1">';



	htmlJuridica = '<label class="label" id="lbl_pessoa_juridica" for="taxvat"><span><?=__('CNPJ')?></span></label>';
	htmlJuridica += '<div class="control">';
	htmlJuridica += '	<input type="text" id="taxvat" onchange="buscarTaxVat(this)" onkeyup="mascaraMutuario(this,cpfCnpj)" name="taxvat" value="" title="<?=__('CNPJ')?>" class="input-text " data-validate="{required:true}" autocomplete="off" aria-required="true">';
	htmlJuridica += '</div>';
	htmlJuridica += '<input type="hidden" name="tipo_pessoa" value="2">';

	<?php if($scopeConfig->getValue("mmcpfcnpj/loja/razao_social", $storeScope)): ?>
	htmlJuridica += '<label class="label" for="rasao_social"><span><?=__('Rasão Social')?></span></label>';
	htmlJuridica += '<div class="control">';
	htmlJuridica += '	<input type="text" id="rasao_social" name="rasao_social" value="" title="<?=__('Rasão Social')?>" class="input-text " data-validate="{required:true}" autocomplete="off" aria-required="true">';
	htmlJuridica += '</div>';
	<?php endif; ?>

	<?php if($scopeConfig->getValue("mmcpfcnpj/loja/inscricao_estadual", $storeScope)): ?>
	htmlJuridica += '<label class="label" for="inscricao_estadual"><span><?=__('Inscrição Estadual')?></span></label>';
	htmlJuridica += '<div class="control">';
	htmlJuridica += '	<input type="text" id="inscricao_estadual" name="inscricao_estadual" value="" title="<?=__('Inscrição Estadual')?>" class="input-text " data-validate="{required:true}" autocomplete="off" aria-required="true">';
	htmlJuridica += '</div>';
	<?php endif; ?>

var tipo_pessoa = "<?=$tipo_pessoa?>";
var rasao_social = "<?=$rasao_social?>";
var inscricao_estadual = "<?=$inscricao_estadual?>";
var taxvat = "<?=$taxvat?>";
	require([
		"jquery",
		"jquery/ui"
	], function($){
		$(".taxvat").html(htmlCheck);
		$(".cont_check_mm").html(htmlFisica);

		$("#taxvat").attr('maxlength','14');
		if(tipo_pessoa == 2){
			$(".cont_check_mm").html(htmlJuridica);
			$("#taxvat").attr('maxlength','18');
		}


		$('#inscricao_estadual').val(inscricao_estadual);
		$('#rasao_social').val(rasao_social);

		$('#taxvat').val(taxvat);
		$('input.cls_tipo_pessoa').change(function() {
			if(this.checked) {
				if(this.value == 1){
					$(".cont_check_mm").html(htmlFisica);
					$("input#taxvat").attr('value',(tipo_pessoa == this.value ? taxvat : '' )).attr('maxlength','14');
				}else if(this.value == 2){
					$(".cont_check_mm").html(htmlJuridica);
					$("input#taxvat").attr('value',(tipo_pessoa == this.value ? taxvat : '' )).attr('maxlength','18');
				}
			}
			$('#inscricao_estadual').val(inscricao_estadual);
			$('#rasao_social').val(rasao_social);

		});


	});
</script>

<script>
	function mascaraMutuario(o,f){
		v_obj=o;
		v_fun=f;
		setTimeout('execmascara()',1)
	}

	function execmascara(){
		v_obj.value=v_fun(v_obj.value)
	}

	function cpfCnpj(v){
		v=v.replace(/\D/g,"");
		if (v.length > 0 && v.length <= 11) {
			//CPF
			v=v.replace(/(\d{3})(\d)/,"$1.$2");
			v=v.replace(/(\d{3})(\d)/,"$1.$2");
			v=v.replace(/(\d{3})(\d{1,2})$/,"$1-$2")
		} else {
			//CNPJ
			v=v.replace(/^(\d{2})(\d)/,"$1.$2");
			v=v.replace(/^(\d{2})\.(\d{3})(\d)/,"$1.$2.$3");
			v=v.replace(/\.(\d{3})(\d)/,".$1/$2");
			v=v.replace(/(\d{4})(\d)/,"$1-$2");
		}
		return v
	}


	function buscarTaxVat(val) {
		validaCampo(val.value);
		<?php if($scopeConfig->getValue("mmcpfcnpj/loja/taxvat_unico", $storeScope)): ?>
		if(validaCampo(val.value)) {
			var xmlhttp = new XMLHttpRequest();
			xmlhttp.onreadystatechange = function () {
				if (this.readyState == 4 && this.status == 200) {

					var taxvat = document.querySelector('#taxvat');


					var labelTipoDoc = '';
					if (document.querySelector('#pessoa_fisica').checked) {
						labelTipoDoc = 'CPF';
					} else {
						labelTipoDoc = 'CNPJ';
					}

					if (this.responseText == 1) {

						if (!document.querySelector('.cpf-cnpj-mm')) {
							taxvat.insertAdjacentHTML('afterend', '<div class="field-error cpf-cnpj-mm" data-bind="attr: { id: element.errorId }" generated="true" id="cpf-cnpj-mm"><span data-bind="text: element.error">' + labelTipoDoc + ' já cadastrado, <a href="<?php echo  $baseUrl ?>customer/account/forgotpassword/"> clique aqui para se logar </a> </span></div>');
						}
						taxvat.style.border = "1px solid #ed8380";
						document.querySelector('.cpf-cnpj-mm').style.display = "Block";
						document.querySelector('.actions-toolbar > .primary .action:last-child').style.display = "none";
					} else {
						if (document.querySelector('.cpf-cnpj-mm'))
							document.querySelector('.cpf-cnpj-mm').style.display = "none";

						document.querySelector('.actions-toolbar > .primary .action:last-child').style.display = "Block";
						taxvat.style.border = "1px solid #c2c2c2";
					}


				}
			};
			xmlhttp.open("GET", "<?php echo  $baseUrl ?>mestremage_cpfcnpj?taxvat=" + val.value + "&_=" + Date.now(), true);
			xmlhttp.send();
		}
<?php endif; ?>
	}


</script>
<style>
	.cont_check_mm label.label {
		font-weight: 600;
		margin: 0 0 8px;
		display: inline-block;
	}
	.cont_check_mm label.label:after {
		content: '*';
		color: #e02b27;
		font-size: 1.2rem;
		margin: 0 0 0 5px;
	}
	.cont_check_mm .control {
		margin: 0 0 20px;
	}
	.cont_pessoa > label {
		margin-right: 20px;
	}
</style>
<?php endif; ?>

<script>
	function validaCampo(object) {
		var taxvat = document.querySelector('#taxvat');

		if(object.indexOf("11111")!=-1 ||
			object.indexOf("22222")!=-1 ||
			object.indexOf("33333")!=-1 ||
			object.indexOf("44444")!=-1 ||
			object.indexOf("55555")!=-1 ||
			object.indexOf("66666")!=-1 ||
			object.indexOf("77777")!=-1 ||
			object.indexOf("88888")!=-1 ||
			object.indexOf("99999")!=-1) {
			errorReturn();
			return false;
		}


		if (object.length <= 14) {

			if(document.querySelector('#pessoa_juridic').checked){
				errorReturn();
				return false;
			}else{
				sucessReturn();
				return ValidarCPF(object)
			}
		} else {
			return ValidarCNPJ(object)
		}
	}
	//valida o CPF digitado
	function ValidarCPF(Objcpf) {
		var cpf = Objcpf;
		var exp = /\.|\-/g;
		cpf = cpf.toString().replace(exp, "");


		if (VerificaCPF(cpf)) {
			sucessReturn();
		} else {
			errorReturn();
		}
		return VerificaCPF(cpf);
	}
	//valida o CNPJ digitado
	function ValidarCNPJ(ObjCnpj) {

		var cnpj = ObjCnpj;
		var valida = new Array(6, 5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2);
		var dig1 = new Number;
		var dig2 = new Number;

		exp = /\.|\-|\//g;
		cnpj = cnpj.toString().replace(exp, "");
		var digito = new Number(eval(cnpj.charAt(12) + cnpj.charAt(13)));

		for (i = 0; i < valida.length; i++) {
			dig1 += (i > 0 ? (cnpj.charAt(i - 1) * valida[i]) : 0);
			dig2 += cnpj.charAt(i) * valida[i];
		}
		dig1 = (((dig1 % 11) < 2) ? 0 : (11 - (dig1 % 11)));
		dig2 = (((dig2 % 11) < 2) ? 0 : (11 - (dig2 % 11)));

		if (((dig1 * 10) + dig2) != digito) {
			errorReturn();
			return false;
		} else {
			sucessReturn();
			return true;
		}

	}

	function sucessReturn(){
		var taxvat = document.querySelector('#taxvat');
		if(document.querySelector('.cpf-cnpj-mm-val')){
			document.querySelector('.cpf-cnpj-mm-val').style.display = "none";
		}


		document.querySelector('.actions-toolbar > .primary .action:last-child').disabled = false;
		taxvat.style.border = "1px solid #c2c2c2";
	}
	function errorReturn(){
		var taxvat = document.querySelector('#taxvat');
		if (!document.querySelector('.cpf-cnpj-mm-val')) {
			taxvat.insertAdjacentHTML('afterend', '<div class="field-error cpf-cnpj-mm-val" data-bind="attr: { id: element.errorId }" generated="true" id="cpf-cnpj-mm-val"><span data-bind="text: element.error"> CPF/CNPJ Inválido </span></div>');
		}
		taxvat.value = "";
		taxvat.style.border = "1px solid #ed8380";
		document.querySelector('.cpf-cnpj-mm-val').style.display = "Block";
		document.querySelector('.actions-toolbar > .primary .action:last-child').disabled = true;
	}

	function VerificaCPF(strCpf) {

		var soma;
		var resto;
		soma = 0;
		if (strCpf == "00000000000") {
			return false;
		}

		for (i = 1; i <= 9; i++) {
			soma = soma + parseInt(strCpf.substring(i - 1, i)) * (11 - i);
		}

		resto = soma % 11;

		if (resto == 10 || resto == 11 || resto < 2) {
			resto = 0;
		} else {
			resto = 11 - resto;
		}

		if (resto != parseInt(strCpf.substring(9, 10))) {
			return validarCpf2(strCpf);
		}

		soma = 0;

		for (i = 1; i <= 10; i++) {
			soma = soma + parseInt(strCpf.substring(i - 1, i)) * (12 - i);
		}
		resto = soma % 11;

		if (resto == 10 || resto == 11 || resto < 2) {
			resto = 0;
		} else {
			resto = 11 - resto;
		}

		if (resto != parseInt(strCpf.substring(10, 11))) {
			return validarCpf2(strCpf);
		}

		return true;
	}


	function validarCpf2(strCPF) {
		var Soma;
		var Resto;
		Soma = 0;
		if (strCPF == "00000000000") return false;

		for (i=1; i<=9; i++) Soma = Soma + parseInt(strCPF.substring(i-1, i)) * (11 - i);
		Resto = (Soma * 10) % 11;

		if ((Resto == 10) || (Resto == 11))  Resto = 0;
		if (Resto != parseInt(strCPF.substring(9, 10)) ) return false;

		Soma = 0;
		for (i = 1; i <= 10; i++) Soma = Soma + parseInt(strCPF.substring(i-1, i)) * (12 - i);
		Resto = (Soma * 10) % 11;

		if ((Resto == 10) || (Resto == 11))  Resto = 0;
		if (Resto != parseInt(strCPF.substring(10, 11) ) ) return false;
		return true;
	}

</script>


