<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$_config  = $this->helper('Sm\Market\Helper\Data');
$tabStyle = $_config->getProductDetail('tab_style');

$show_custom_tab   = $_config->getProductDetail('show_custom_tab');
$custom_tab_name   = $_config->getProductDetail('custom_tab_name');
$customtab_content = $_config->getProductDetail('customtab_content');
?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')): ?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>


        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                $html = $layout->renderElement($name);
                if (!trim($html)) {
                    continue;
                }
                $alias = $layout->getElementAlias($name);
                $label = $block->getChildData($alias, 'title');
                ?>
                <div class="product-description" id="<?= /* @escapeNotVerified */ $alias ?>" data-role="content">
                    <div class="details-goto-section flex-row-center">
                        <span class="mdc-typography--headline4 description-title">Descrição do Produto</span>
                        <div class="details-goto flex-row-center mobile-none">
                            <a href="#product-dimension" class="mdc-button details-goto-button">dimensões do produto</a>
                            <a href="#product-specification" class="mdc-button details-goto-button">especificações técnicas</a>
                        </div>
                    </div>
                    <div class="mdc-typography--body1 description-text">
                        <?= /* @escapeNotVerified */ $html ?>
                    </div>
                    <div class="details-goto flex-column display-none mobile-display">
                        <a href="#product-dimension" class="mdc-typography--body1 details-goto-label">Dimensões do Produto</a>
                        <a href="#product-specification" class="mdc-typography--body1 details-goto-label">Especificações Técnicas</a>
                    </div>
                </div>
            <?php endforeach;?>
        </div>
    </div>
<?php endif; ?>
