<?php $_product = $block->getProduct(); ?>
<div id="product-specification" class="mdc-layout-grid mdc-layout-grid--fixed-column-width">
    <div class="mdc-layout-grid__inner no-padding">
        <div class="mdc-layout-grid__cell--span-1-desktop mobile-none"></div>
        <div class="mdc-layout-grid__cell--span-10-desktop mdc-layout-grid__cell--span-8-tablet mdc-layout-grid__cell--span-4-phone">
            <div class="specification-title">
                <span class="mdc-typography--headline5 specification-title-text">Especificações Técnicas</span>
            </div>
            <div class="bordaespec">
              <table>
                <?php
                $detalhes = explode("\n", $_product->getData('atributos_temporarios'));
                foreach($detalhes as $detalhe) {
                  $detec = explode(":",$detalhe);
                  echo '<tr><td class="col-lg-3 col-md-2 col-sm-4 col-xs-4">'.$detec[0].'</td>';
                    if(isset($detec[1])){
                      echo '<td class="col-lg-9 col-md-10 col-sm-8 col-xs-8">'.$detec[1].'</td></tr>';
                    } else {
                      echo '<td class="col-lg-9 col-md-10 col-sm-8 col-xs-8">&nbsp;</td></tr>';
                    }
                }
                ?>
              </table>
            </div>
        </div>
    </div>
</div>
