<?php
/**
 * Copyright © Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block Magmodules\GoogleShopping\Block\Adminhtml\System\Config\Form\Feeds
 */
?>
<?php if ($feedData = $block->getFeedData()): ?>
    <div class="mm-block-googleshopping-feeds">
        <table class="mm-block-googleshopping-feed-table">
            <thead>
                <span class="title">Feeds</span>
                All active feeds are shown in the overview below.<br>The .XML URL is the URL which needs to
                be copied and pasted into you Google Merchant Account. In relation to cache settings in the
                browser, it is advised that you download the Feed to make sure that you are viewing the
                latest version. There is a small note at the end of the XML file where you can find the
                time of generation and the number of products.<br><br><strong>Note:</strong>
                Make sure that you save the configuration after the settings have been changed and before
                you generate the feed.
            </thead>
            <tbody>
                <?php foreach ($feedData as $data): ?>
                    <tr>
                        <td>
                            <p><?= $block->escapeHtml($data['name']); ?></p>
                            <p>
                                <small><?= $block->escapeHtml($data['code']); ?></small>
                            </p>
                        </td>
                        <td>
                            <?php if (!empty($data['feed']) && $data['available']): ?>
                                <p>
                                    <a href="<?= $block->escapeUrl($data['feed']); ?>" target="_blank">
                                        <?= $block->escapeHtml($data['feed']); ?>
                                    </a>
                                </p>
                                <p>
                                    <small><?= $block->escapeHtml($data['result']); ?></small>
                                </p>
                            <?php else: ?>
                                <p>
                                    <?= $block->escapeHtml($data['feed']); ?>
                                </p>
                                <p>
                                    <small>
                                        <?= $block->escapeHtml(__('Feed not available, please generate the feed first.')) ?>
                                    </small>
                                </p>
                            <?php endif; ?>
                        </td>
                        <td>
                            <?php if (!empty($data['status'])): ?>
                                <p>
                                    <a class="generate"
                                       href="<?= $block->escapeUrl($block->getGenerateUrl($data['store_id'])); ?>">Generate</a>
                                </p>
                                <p>
                                    <a class="preview" href="<?= $block->escapeUrl($block->getPreviewUrl($data['store_id'])); ?>"
                                       target="_blank">Preview</a>
                                </p>
                                <p>
                                    <?php if (!empty($data['full_path']) && $data['available']): ?>
                                        <a class="download"
                                           href="<?= $block->escapeUrl($block->getDownloadUrl($data['store_id'])); ?>">Download</a>
                                    <?php endif; ?>
                                </p>
                            <?php else: ?>
                                <p class="enable">
                                    <?= $block->escapeHtml(__('Feed Generation Disabled.')) ?>
                                    <small>
                                        <br>
                                        <?= $block->escapeHtml(__('Enabled the Feed under the Settings above.')) ?>
                                    </small>
                                </p>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php endif; ?>