<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Storelocator
 */
?>
<?php /** @var \Amasty\Storelocator\Block\Location $block */ ?>
<?php

$productId = (int)$block->getRequest()->getParam('product');

if ($productId):
    $product = $block->getProductById($productId);
    ?>
    <h1><?= $block->escapeHtml($product->getName()); ?><?= $block->escapeHtml(__(' can be found at the following stores:&nbsp;')); ?></h1>
    <hr>
<?php endif; ?>
<div class="amlocator-main-container" style="<?= $block->escapeHtml($block->getMainBlockStyles()); ?>">
    <?php if ($block->getWidgetDescription()): ?>
        <div>
            <strong><?= $block->escapeHtml($block->getWidgetDescription()); ?></strong>
        </div>
    <?php endif; ?>
    <div class="amlocator-map-container" id="<?= $block->escapeHtml($block->getMapContainerId()); ?>">
        <?php if ($block->getShowSearch()): ?>
            <div class="amlocator-search-container">
                <div class="amlocator-block -current amlocator-current-location">
                    <div class="amlocator-wrapper">
                        <input type="text" value="" class="amlocator-text"
                               name="address" placeholder="<?= $block->escapeHtml(__('Localiza&ccedil;&atilde;o Atual')); ?>"
                               data-amlocator-js="address"
                               autocomplete="off">
                        <span class="amlocator-search" data-amlocator-js="search"></span>
                        <span class="amlocator-reset -hidden" data-amlocator-js="reset"></span>
                    </div>
                </div>
                <div class="amlocator-block -search amlocator-search-radius">
                    <label class="amlocator-title" id="range_radius" for="radius">
                        <?= $block->escapeHtml(__('Raio de Pesquisa')); ?>
                    </label>
                    <?php if ($block->getDistanceConfig() == 'choose'): ?>
                        <select class="amlocator-select -measurement" id="amlocator-measurement"
                                name="measurement" data-amlocator-js="measurment-select">
                            <option value="km"><?= $block->escapeHtml(__('km')); ?></option>
                            <option selected="selected" value="mi"><?= $block->escapeHtml(__('mi')); ?></option>
                        </select>
                    <?php else:?>
                        <label>, <?= $block->escapeHtml($block->getDistanceConfig()) ?></label>
                    <?php endif ?>
                    <div class="amlocator-wrapper">
                        <?php if ($block->getRadiusType() == 'select' || empty($block->getRadiusType())): ?>
                            <select class="amlocator-select" data-amlocator-js="radius-select" name="radius" >
                                <?php foreach ($block->getSearchRadius() as $range): ?>
                                    <option value="<?= is_numeric($range) ? (int)$range : ''; ?>">
                                        <?= $block->escapeHtml($range) ?>
                                    </option>
                                <?php endforeach;?>
                            </select>
                        <?php else:?>
                            <div class="amlocator-range-slider" data-amlocator-js="range-slider">
                                <div class="amlocator-handle ui-slider-handle">
                                    <div class="amlocator-tooltip">
                                        <span data-amlocator-js="radius-value"></span>
                                        <span data-amlocator-js="radius-measurment">
                                        <?= ($block->getDistanceConfig() != 'choose')
                                            ? $block->escapeHtml($block->getDistanceConfig())
                                            : '' ?>
                                    </span>
                                    </div>
                                </div>
                            </div>
                            <input type="hidden" name="radius"
                                   data-amlocator-js="radius-select"
                                   value="<?= (int)$block->getMaxRadiusValue(); ?>"
                                   min="<?= (int)$block->getMinRadiusValue(); ?>"
                                   max="<?= (int)$block->getMaxRadiusValue(); ?>"/>
                        <?php endif ?>
                    </div>
                </div>
                <div class="amlocator-block -separator"><hr class="hr"/></div>
                <button class="amlocator-button -nearby"
                        title="<?= $block->escapeHtml(__('Localizar nas proximidades')); ?>" style="background: #003583 !important;">
                    <?= $block->escapeHtml(__('Localizar nas proximidades')); ?>
                </button>
                <div class="amlocator-block -separator"><hr class="hr"/></div>
            </div>
        <?php endif; ?>
        <?php if ($block->getShowLocations()): ?>
            <?php if ($attributes = $block->getAttributes()): ?>
                <div class="amlocator-block -filter">
                    <div class="amlocator-filters-container">
                        <div class="amlocator-title amlocator-attribute-filter"
                             data-amlocator-js="filters-title">
                            <span><?= $block->escapeHtml(__('Filtro')); ?></span>
                            <span class="amlocator-arrow <?=
                            $block->escapeHtml($block->getFilterClass()) ? ' -down' : '';
                            ?>">
                            </span>
                        </div>
                        <div class="amlocator-content<?= $block->escapeHtml($block->getFilterClass()); ?>"
                             data-amlocator-js="filters-container">
                            <?php $attributes = $block->getAttributes();?>
                            <form class="attributes" action="#" data-amlocator-js="attributes-form">
                                <?php foreach ($attributes as $attribute): ?>
                                    <div class="amlocator-attribute-wrapper">
                                        <div class="amlocator-label"><?= $block->escapeHtml($attribute['label']); ?></div>
                                        <div class="amlocator-input">
                                            <select name="<?= (int)$attribute['attribute_id'];?>"
                                                    class="amlocator-select"
                                                <?php if ($attribute['frontend_input'] == 'multiselect'): ?>
                                                    multiple="multiple"
                                                    data-amlocator-js="multiple-select"
                                                <?php endif;?>>
                                                <?php if ($attribute['frontend_input'] != 'multiselect'):?>
                                                    <option value="" selected><?= $block->escapeHtml(__('Selecione')); ?></option>
                                                <?php endif?>
                                                <?php foreach ($attribute['options'] as $valueId => $option): ?>
                                                    <option
                                                        <?php if ($block->isOptionSelected(
                                                            $attribute,
                                                            $option
                                                        )): ?>
                                                            selected
                                                        <?php endif; ?>
                                                        value="<?= (int)$option['value'] ?>">
                                                        <?= $block->escapeHtml(
                                                            $option['label']
                                                        ); ?>
                                                    </option>
                                                <?php endforeach;?>
                                            </select>
                                        </div>
                                    </div>
                                <?php endforeach;?>
                            </form>
                            <div class="amlocator-actions">
                                <span class="amlocator-clear"
                                   title="<?= $block->escapeHtml(__('Limpar')); ?>"
                                   data-amlocator-js="clear-filters">
                                    <?= $block->escapeHtml(__('Limpar')); ?>
                                </span>
                                <button class="amlocator-button amlocator-filter-attribute"
                                        title="<?= $block->escapeHtml(__('Filtro')) ?>">
                                    <?= $block->escapeHtml(__('Filtro')); ?>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
            <div class="amlocator-block -storelist amlocator-store-list">
                <?= $block->getLeftBlockHtml(); ?>
            </div>
        <?php endif; ?>
        <div class="amlocator-block -map">
            <div class="amlocator-map" id="<?= $block->escapeHtml($block->getMapId()); ?>"></div>
        </div>
    </div>
</div>

<script>
    require([
        'jquery',
        'Amasty_Storelocator/js/main',
        'Amasty_Storelocator/js/cluster',
        'domReady!',
        'https://maps.googleapis.com/maps/api/js?libraries=places&key=<?= $block->escapeHtml(
            $block->configProvider->getApiKey()
        ); ?>'
    ], function ($) {
        var mapId = "#" + "<?= $block->escapeHtml($block->getMapId()); ?>";
        $(mapId).amLocator({
            amMediaUrl :"<?= $block->escapeHtml($block->getAmStoreMediaUrl()); ?>",
            mapZoom: <?= $block->escapeHtml($block->getMapZoom()); ?>,
            productId: "<?= (int)$block->getProductId() ?>",
            categoryId: "<?= (int)$block->getCategoryId() ?>",
            automaticLocate: "<?= (bool)$block->getAutomaticLocate(); ?>",
            enableClustering: "<?= (bool)$block->getClustering(); ?>",
            enableSuggestionClickSearch: "<?= (bool)$block->getSuggestionClickSearch(); ?>",
            enableCountingDistance: "<?= (bool)$block->getCountingDistance(); ?>",
            distanceConfig: "<?= $block->escapeHtml($block->getDistanceConfig()); ?>",
            useGeoConfig: "<?= (bool)$block->getGeoUse()?>",
            allowedCountries: <?= /* @noEscape */ $block->getAllowedCountries(); ?>,
            ajaxCallUrl: "<?= $block->escapeHtml(
                $block->getUrl('amlocator/index/ajax') . $block->getQueryString()
            ); ?>",
            useBrowserLocation: "<?= (bool)$block->getUseBrowserLocation()?>",
            jsonLocations: <?= /* @noEscape */ $block->getJsonLocations() ?>,
            imageLocations: "<?= $block->escapeHtml($block->getViewFileUrl('Amasty_Storelocator::images/')); ?>",
            mapId : "<?= $block->escapeHtml($block->getMapId()); ?>",
            mapContainerId: "<?= $block->escapeHtml($block->getMapContainerId()); ?>",
            showSearch: <?= (int)$block->getShowSearch(); ?>,
            <?php if ($block->getRadiusType() == 'range'):?>
                isRadiusSlider: <?= $block->escapeHtml($block->getRadiusType()) == 'range'?>,
                maxRadiusValue: <?= (int)$block->getMaxRadiusValue(); ?>,
                minRadiusValue: <?= (int)$block->getMinRadiusValue(); ?>,
                measurementRadius: "<?= ($block->getDistanceConfig() != 'choose') ?
                    $block->escapeHtml($block->getDistanceConfig()) : ''?>"
            <?php endif;?>
        });
    });
</script>
