<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Storelocator
 */
?>
<?php
/** @var \Amasty\Storelocator\Block\Location $block */
if ($block->getProduct()) {
    if (!$block->getRequest()->getParam("product")) {
        $productId = $block->getProduct()->getId();
    }
    $locationCollection = $block->getLocationCollection();

    if (count($locationCollection) > 0 && $block->validateLocations($locationCollection, $block->getProduct())) {
        $target = $block->getTarget();
        $linkText = $block->getLinkText();
        echo '<div style="clear: both"><a href="' . $block->escapeHtml($block->getLinkToMap(["product" => $productId]))
            . '"' . $block->escapeHtml($target) . '>' . $block->escapeHtml($linkText) . '</a></div>';
    }
}
