<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var \Magento\Wishlist\Block\Link $block */
?>
    <div class="link wishlist" data-bind="scope: 'wishlist'">
        <a <?= /* @noEscape */ $block->getLinkAttributes() ?>>
        <img src="/pub/static/frontend/Sm/market/pt_BR/images/favorite-icon.png">
            
        </a>
    </div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "wishlist": {
                        "component": "Magento_Wishlist/js/view/wishlist"
                    }
                }
            }
        }
    }

</script>
